// App data for the portal
// URLs can be updated to GitHub Pages URLs when deployed
const APP_DATA = [
    {
        id: 'quiz-app',
        name: '지식 퀴즈',
        shortDesc: '일반상식 테스트',
        description: '재미있는 지식 퀴즈로 상식을 쌓아보세요! 100개의 다양한 문제에 도전하세요.',
        icon: '🧠',
        color: '#667eea',
        category: 'brain',
        tags: ['퀴즈', '상식', '교육', '게임', 'quiz', 'knowledge', 'education', 'game'],
        url: 'https://dopabrain.com/quiz-app/',
        isNew: false,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Knowledge Quiz', shortDesc: 'General knowledge test' },
            zh: { name: '知识问答', shortDesc: '常识测试' },
            hi: { name: 'ज्ञान क्विज़', shortDesc: 'सामान्य ज्ञान परीक्षा' },
            ru: { name: 'Викторина', shortDesc: 'Тест на общие знания' },
            ja: { name: '知識クイズ', shortDesc: '一般常識テスト' },
            es: { name: 'Quiz de Conocimiento', shortDesc: 'Test de cultura general' },
            pt: { name: 'Quiz de Conhecimento', shortDesc: 'Teste de conhecimentos gerais' },
            id: { name: 'Kuis Pengetahuan', shortDesc: 'Tes pengetahuan umum' },
            tr: { name: 'Bilgi Yarışması', shortDesc: 'Genel kültür testi' },
            de: { name: 'Wissensquiz', shortDesc: 'Allgemeinwissen-Test' },
            fr: { name: 'Quiz de Culture', shortDesc: 'Test de culture générale' }
        }
    },
    {
        id: 'shopping-calc',
        name: '글로벌 쇼핑 계산기',
        shortDesc: '환율/관세/팁 계산',
        description: '해외직구와 여행을 위한 환율, 관세, 팁 계산기. 실시간 환율 API 연동.',
        icon: '🛒',
        color: '#f39c12',
        category: 'tool',
        tags: ['환율', '계산기', '관세', '해외직구', '여행', 'currency', 'calculator', 'shopping', 'travel', 'exchange'],
        url: 'https://dopabrain.com/shopping-calc/',
        isNew: false,
        isPopular: true,
        popularity: 5,
        i18n: {
            en: { name: 'Shopping Calculator', shortDesc: 'Currency / duty / tip calc' },
            zh: { name: '全球购物计算器', shortDesc: '汇率/关税/小费计算' },
            hi: { name: 'शॉपिंग कैलकुलेटर', shortDesc: 'मुद्रा/शुल्क/टिप गणना' },
            ru: { name: 'Калькулятор покупок', shortDesc: 'Валюта / пошлина / чаевые' },
            ja: { name: 'ショッピング計算機', shortDesc: '為替/関税/チップ計算' },
            es: { name: 'Calculadora de Compras', shortDesc: 'Divisa / arancel / propina' },
            pt: { name: 'Calculadora de Compras', shortDesc: 'Câmbio / taxa / gorjeta' },
            id: { name: 'Kalkulator Belanja', shortDesc: 'Kurs / bea / tip' },
            tr: { name: 'Alışveriş Hesaplayıcı', shortDesc: 'Döviz / gümrük / bahşiş' },
            de: { name: 'Shopping-Rechner', shortDesc: 'Währung / Zoll / Trinkgeld' },
            fr: { name: 'Calculateur Shopping', shortDesc: 'Devise / douane / pourboire' }
        }
    },
    {
        id: 'detox-timer',
        name: '디지털 디톡스 타이머',
        shortDesc: '스마트폰 사용 관리',
        description: '스마트폰 사용 시간을 줄이고 집중력을 높이세요. 통계와 배지 시스템.',
        icon: '⏰',
        color: '#00b894',
        category: 'wellness',
        tags: ['타이머', '디톡스', '집중', '생산성', 'timer', 'detox', 'focus', 'productivity', 'screentime'],
        url: 'https://dopabrain.com/detox-timer/',
        isNew: false,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'Digital Detox Timer', shortDesc: 'Screen time manager' },
            zh: { name: '数字排毒计时器', shortDesc: '手机使用管理' },
            hi: { name: 'डिजिटल डिटॉक्स टाइमर', shortDesc: 'स्क्रीन टाइम प्रबंधन' },
            ru: { name: 'Цифровой детокс', shortDesc: 'Управление экранным временем' },
            ja: { name: 'デジタルデトックスタイマー', shortDesc: 'スクリーンタイム管理' },
            es: { name: 'Temporizador Detox Digital', shortDesc: 'Gestión del tiempo de pantalla' },
            pt: { name: 'Timer de Detox Digital', shortDesc: 'Gerenciador de tempo de tela' },
            id: { name: 'Timer Detoks Digital', shortDesc: 'Pengatur waktu layar' },
            tr: { name: 'Dijital Detoks Zamanlayıcı', shortDesc: 'Ekran süresi yönetimi' },
            de: { name: 'Digital-Detox-Timer', shortDesc: 'Bildschirmzeit-Manager' },
            fr: { name: 'Minuteur Détox Numérique', shortDesc: 'Gestion du temps d\'écran' }
        }
    },
    {
        id: 'dream-fortune',
        name: '꿈해몽 & 운세',
        shortDesc: 'AI 꿈 해석 & 오늘의 운세',
        description: 'AI 꿈해몽과 오늘의 운세를 확인하세요. 별자리, 타로, 꿈 해석까지!',
        icon: '🔮',
        color: '#9b59b6',
        category: 'fortune',
        tags: ['운세', '꿈해몽', '타로', '별자리', 'fortune', 'dream', 'horoscope', 'tarot', 'zodiac'],
        url: 'https://dopabrain.com/dream-fortune/',
        isNew: false,
        isPopular: true,
        popularity: 10,
        i18n: {
            en: { name: 'Dream & Fortune', shortDesc: 'AI dream reading & horoscope' },
            zh: { name: '解梦与运势', shortDesc: 'AI解梦 & 今日运势' },
            hi: { name: 'सपने और भाग्य', shortDesc: 'AI स्वप्न व्याख्या और राशिफल' },
            ru: { name: 'Сны и гороскоп', shortDesc: 'AI толкование снов и гороскоп' },
            ja: { name: '夢占い & 運勢', shortDesc: 'AI夢診断 & 今日の運勢' },
            es: { name: 'Sueños y Fortuna', shortDesc: 'Interpretación de sueños con IA' },
            pt: { name: 'Sonhos e Fortuna', shortDesc: 'Interpretação de sonhos com IA' },
            id: { name: 'Mimpi & Ramalan', shortDesc: 'Tafsir mimpi AI & ramalan hari ini' },
            tr: { name: 'Rüya & Fal', shortDesc: 'AI rüya yorumu ve günlük burç' },
            de: { name: 'Traum & Horoskop', shortDesc: 'KI-Traumdeutung & Horoskop' },
            fr: { name: 'Rêves & Horoscope', shortDesc: 'Interprétation des rêves par IA' }
        }
    },
    {
        id: 'affirmation',
        name: '일일 긍정 확언 카드',
        shortDesc: '매일 새로운 긍정 메시지',
        description: '매일 새로운 긍정 확언으로 하루를 시작하세요. 자존감, 동기부여, 감사.',
        icon: '💖',
        color: '#e91e63',
        category: 'wellness',
        tags: ['긍정', '확언', '동기부여', '자존감', '명언', 'affirmation', 'motivation', 'positive', 'daily', 'quotes'],
        url: 'https://dopabrain.com/affirmation/',
        isNew: false,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'Daily Affirmation', shortDesc: 'Positive messages every day' },
            zh: { name: '每日正能量卡片', shortDesc: '每天新的正面信息' },
            hi: { name: 'दैनिक सकारात्मक संदेश', shortDesc: 'रोज़ नए प्रेरक संदेश' },
            ru: { name: 'Ежедневные аффирмации', shortDesc: 'Позитивные послания каждый день' },
            ja: { name: '毎日のアファメーション', shortDesc: '毎日のポジティブメッセージ' },
            es: { name: 'Afirmación Diaria', shortDesc: 'Mensajes positivos cada día' },
            pt: { name: 'Afirmação Diária', shortDesc: 'Mensagens positivas todo dia' },
            id: { name: 'Afirmasi Harian', shortDesc: 'Pesan positif setiap hari' },
            tr: { name: 'Günlük Olumlamalar', shortDesc: 'Her gün pozitif mesajlar' },
            de: { name: 'Tägliche Affirmation', shortDesc: 'Positive Botschaften jeden Tag' },
            fr: { name: 'Affirmation Quotidienne', shortDesc: 'Messages positifs chaque jour' }
        }
    },
    {
        id: 'lottery',
        name: '행운의 번호 생성기',
        shortDesc: '로또/연금복권 번호',
        description: '로또 6/45, 연금복권 행운 번호 생성기. 번호 통계 분석, 반자동 모드.',
        icon: '🎰',
        color: '#e74c3c',
        category: 'fortune',
        tags: ['로또', '복권', '번호', '행운', '추첨', 'lottery', 'lucky', 'number', 'generator', 'random'],
        url: 'https://dopabrain.com/lottery/',
        isNew: false,
        isPopular: true,
        popularity: 6,
        i18n: {
            en: { name: 'Lucky Number Generator', shortDesc: 'Lottery number picker' },
            zh: { name: '幸运号码生成器', shortDesc: '彩票号码生成' },
            hi: { name: 'लकी नंबर जनरेटर', shortDesc: 'लॉटरी नंबर चयन' },
            ru: { name: 'Генератор чисел', shortDesc: 'Выбор номеров лотереи' },
            ja: { name: 'ラッキーナンバー生成器', shortDesc: '宝くじ番号ピッカー' },
            es: { name: 'Generador de Números', shortDesc: 'Selector de números de lotería' },
            pt: { name: 'Gerador de Números', shortDesc: 'Seletor de números da loteria' },
            id: { name: 'Generator Angka Keberuntungan', shortDesc: 'Pemilih nomor lotere' },
            tr: { name: 'Şanslı Sayı Üretici', shortDesc: 'Piyango numarası seçici' },
            de: { name: 'Glückszahlen-Generator', shortDesc: 'Lottozahlen-Picker' },
            fr: { name: 'Générateur de Numéros', shortDesc: 'Sélecteur de numéros de loterie' }
        }
    },
    {
        id: 'dday-counter',
        name: 'D-Day 카운터',
        shortDesc: '중요한 날짜 카운트다운',
        description: '중요한 날짜를 D-Day로 관리하세요. 생일, 기념일, 시험일 카운트다운.',
        icon: '📅',
        color: '#3498db',
        category: 'tool',
        tags: ['D-Day', '카운트다운', '기념일', '일정', 'countdown', 'date', 'timer', 'tracker', 'anniversary'],
        url: 'https://dopabrain.com/dday-counter/',
        isNew: false,
        isPopular: false,
        popularity: 3,
        i18n: {
            en: { name: 'D-Day Counter', shortDesc: 'Date countdown tracker' },
            zh: { name: 'D-Day 倒计时', shortDesc: '重要日期倒计时' },
            hi: { name: 'D-Day काउंटर', shortDesc: 'तारीख काउंटडाउन' },
            ru: { name: 'Счётчик D-Day', shortDesc: 'Обратный отсчёт до даты' },
            ja: { name: 'D-Dayカウンター', shortDesc: '日付カウントダウン' },
            es: { name: 'Contador D-Day', shortDesc: 'Cuenta regresiva de fechas' },
            pt: { name: 'Contador D-Day', shortDesc: 'Contagem regressiva de datas' },
            id: { name: 'Penghitung D-Day', shortDesc: 'Hitung mundur tanggal' },
            tr: { name: 'D-Day Sayacı', shortDesc: 'Tarih geri sayımı' },
            de: { name: 'D-Day-Zähler', shortDesc: 'Datums-Countdown' },
            fr: { name: 'Compteur D-Day', shortDesc: 'Compte à rebours de dates' }
        }
    },
    {
        id: 'mbti-tips',
        name: 'MBTI 궁합 & 팁',
        shortDesc: 'MBTI 유형별 분석',
        description: 'MBTI 유형별 궁합, 성격 분석, 연애/직장 팁을 확인하세요.',
        icon: '🧩',
        color: '#1abc9c',
        category: 'test',
        tags: ['MBTI', '성격', '궁합', '심리테스트', 'personality', 'compatibility', 'test', 'types'],
        url: 'https://dopabrain.com/mbti-tips/',
        isNew: false,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'MBTI Compatibility', shortDesc: 'MBTI type analysis & tips' },
            zh: { name: 'MBTI 配对与建议', shortDesc: 'MBTI类型分析' },
            hi: { name: 'MBTI अनुकूलता', shortDesc: 'MBTI प्रकार विश्लेषण' },
            ru: { name: 'MBTI совместимость', shortDesc: 'Анализ типов MBTI' },
            ja: { name: 'MBTI相性 & ヒント', shortDesc: 'MBTIタイプ分析' },
            es: { name: 'Compatibilidad MBTI', shortDesc: 'Análisis de tipos MBTI' },
            pt: { name: 'Compatibilidade MBTI', shortDesc: 'Análise de tipos MBTI' },
            id: { name: 'Kecocokan MBTI', shortDesc: 'Analisis tipe MBTI' },
            tr: { name: 'MBTI Uyumluluk', shortDesc: 'MBTI tip analizi' },
            de: { name: 'MBTI-Kompatibilität', shortDesc: 'MBTI-Typ-Analyse & Tipps' },
            fr: { name: 'Compatibilité MBTI', shortDesc: 'Analyse des types MBTI' }
        }
    },
    {
        id: 'white-noise',
        name: '백색소음 플레이어',
        shortDesc: '집중/수면용 배경음',
        description: '집중, 수면, 명상을 위한 백색소음 & 자연소리 플레이어.',
        icon: '🎵',
        color: '#2c3e50',
        category: 'wellness',
        tags: ['백색소음', '수면', '집중', '명상', 'ASMR', 'whitenoise', 'sleep', 'relaxation', 'sound', 'ambient'],
        url: 'https://dopabrain.com/white-noise/',
        isNew: false,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'White Noise Player', shortDesc: 'Focus & sleep sounds' },
            zh: { name: '白噪音播放器', shortDesc: '专注/睡眠背景音' },
            hi: { name: 'व्हाइट नॉइज़ प्लेयर', shortDesc: 'फोकस और नींद की आवाज़ें' },
            ru: { name: 'Белый шум', shortDesc: 'Звуки для сна и фокуса' },
            ja: { name: 'ホワイトノイズプレーヤー', shortDesc: '集中 & 睡眠用サウンド' },
            es: { name: 'Reproductor Ruido Blanco', shortDesc: 'Sonidos para concentración y sueño' },
            pt: { name: 'Player de Ruído Branco', shortDesc: 'Sons para foco e sono' },
            id: { name: 'Pemutar White Noise', shortDesc: 'Suara fokus & tidur' },
            tr: { name: 'Beyaz Gürültü Oynatıcı', shortDesc: 'Odaklanma ve uyku sesleri' },
            de: { name: 'Weißes-Rauschen-Player', shortDesc: 'Fokus- & Schlafgeräusche' },
            fr: { name: 'Lecteur Bruit Blanc', shortDesc: 'Sons pour la concentration et le sommeil' }
        }
    },
    {
        id: 'dev-quiz',
        name: '개발자 퀴즈',
        shortDesc: '코딩/IT 전문 퀴즈',
        description: '개발자를 위한 코딩/IT 퀴즈. JavaScript, Python, 네트워크 등.',
        icon: '💻',
        color: '#27ae60',
        category: 'dev',
        tags: ['개발자', '코딩', 'IT', '프로그래밍', '퀴즈', 'developer', 'coding', 'programming', 'javascript', 'python'],
        url: 'https://dopabrain.com/dev-quiz/',
        isNew: false,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'Developer Quiz', shortDesc: 'Coding & IT quiz' },
            zh: { name: '开发者测验', shortDesc: '编程/IT专业测验' },
            hi: { name: 'डेवलपर क्विज़', shortDesc: 'कोडिंग और IT क्विज़' },
            ru: { name: 'Квиз разработчика', shortDesc: 'Тест по программированию' },
            ja: { name: '開発者クイズ', shortDesc: 'コーディング & ITクイズ' },
            es: { name: 'Quiz para Desarrolladores', shortDesc: 'Quiz de programación e IT' },
            pt: { name: 'Quiz do Desenvolvedor', shortDesc: 'Quiz de programação e TI' },
            id: { name: 'Kuis Developer', shortDesc: 'Kuis coding & IT' },
            tr: { name: 'Geliştirici Quizi', shortDesc: 'Kodlama ve BT quizi' },
            de: { name: 'Entwickler-Quiz', shortDesc: 'Programmier- & IT-Quiz' },
            fr: { name: 'Quiz Développeur', shortDesc: 'Quiz programmation et IT' }
        }
    },
    {
        id: 'tax-refund-preview',
        name: '연말정산 미리보기',
        shortDesc: '환급액 시뮬레이션',
        description: '연말정산 예상 환급액을 미리 계산해보세요. 소득공제, 세액공제 반영.',
        icon: '💰',
        color: '#3742fa',
        category: 'tool',
        tags: ['연말정산', '환급', '세금', '계산기', 'tax', 'refund', 'calculator', 'finance', 'money'],
        url: 'https://dopabrain.com/tax-refund-preview/',
        isNew: true,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'Tax Refund Calculator', shortDesc: 'Estimate your tax refund' },
            zh: { name: '退税计算器', shortDesc: '退税金额预估' },
            hi: { name: 'टैक्स रिफंड कैलकुलेटर', shortDesc: 'टैक्स रिफंड अनुमान' },
            ru: { name: 'Калькулятор налогов', shortDesc: 'Расчёт возврата налогов' },
            ja: { name: '確定申告シミュレーター', shortDesc: '還付金の試算' },
            es: { name: 'Calculadora de Impuestos', shortDesc: 'Estima tu devolución fiscal' },
            pt: { name: 'Calculadora de Impostos', shortDesc: 'Estime sua restituição' },
            id: { name: 'Kalkulator Pajak', shortDesc: 'Estimasi pengembalian pajak' },
            tr: { name: 'Vergi İadesi Hesaplayıcı', shortDesc: 'Vergi iadenizi tahmin edin' },
            de: { name: 'Steuererstattungsrechner', shortDesc: 'Steuererstattung berechnen' },
            fr: { name: 'Calculateur d\'Impôts', shortDesc: 'Estimez votre remboursement' }
        }
    },
    {
        id: 'unit-converter',
        name: '단위 변환기 Pro',
        shortDesc: '평수, 무게, 온도 변환',
        description: '평수, 무게, 온도, 부피 등 다양한 단위를 실시간으로 변환합니다.',
        icon: '📐',
        color: '#2ed573',
        category: 'tool',
        tags: ['단위', '변환', '평수', '온도', '무게', 'converter', 'unit', 'length', 'weight', 'temperature'],
        url: 'https://dopabrain.com/unit-converter/',
        isNew: true,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'Unit Converter Pro', shortDesc: 'Length, weight, temp converter' },
            zh: { name: '单位转换器 Pro', shortDesc: '长度/重量/温度转换' },
            hi: { name: 'यूनिट कन्वर्टर Pro', shortDesc: 'लंबाई, वज़न, तापमान रूपांतरण' },
            ru: { name: 'Конвертер величин', shortDesc: 'Длина, вес, температура' },
            ja: { name: '単位変換器 Pro', shortDesc: '長さ・重さ・温度の変換' },
            es: { name: 'Conversor de Unidades Pro', shortDesc: 'Longitud, peso, temperatura' },
            pt: { name: 'Conversor de Unidades Pro', shortDesc: 'Comprimento, peso, temperatura' },
            id: { name: 'Konverter Satuan Pro', shortDesc: 'Panjang, berat, suhu' },
            tr: { name: 'Birim Dönüştürücü Pro', shortDesc: 'Uzunluk, ağırlık, sıcaklık' },
            de: { name: 'Einheitenrechner Pro', shortDesc: 'Länge, Gewicht, Temperatur' },
            fr: { name: 'Convertisseur d\'Unités Pro', shortDesc: 'Longueur, poids, température' }
        }
    },
    {
        id: 'sky-runner',
        name: 'Sky Runner',
        shortDesc: '우주 비행 아케이드 게임',
        description: '우주선을 조종해 장애물을 피하세요! 원탭 조작의 중독성 캐주얼 아케이드 게임.',
        icon: '🚀',
        color: '#3b82f6',
        category: 'game',
        tags: ['게임', '아케이드', '우주', '캐주얼', 'Flappy', 'game', 'arcade', 'space', 'casual', 'runner'],
        url: 'https://dopabrain.com/sky-runner/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Sky Runner', shortDesc: 'Space flight arcade game' },
            zh: { name: 'Sky Runner', shortDesc: '太空飞行街机游戏' },
            hi: { name: 'Sky Runner', shortDesc: 'स्पेस फ्लाइट आर्केड गेम' },
            ru: { name: 'Sky Runner', shortDesc: 'Космическая аркада' },
            ja: { name: 'Sky Runner', shortDesc: '宇宙フライトアーケード' },
            es: { name: 'Sky Runner', shortDesc: 'Juego arcade de vuelo espacial' },
            pt: { name: 'Sky Runner', shortDesc: 'Jogo arcade de voo espacial' },
            id: { name: 'Sky Runner', shortDesc: 'Game arkade penerbangan luar angkasa' },
            tr: { name: 'Sky Runner', shortDesc: 'Uzay uçuş arcade oyunu' },
            de: { name: 'Sky Runner', shortDesc: 'Weltraum-Arcade-Spiel' },
            fr: { name: 'Sky Runner', shortDesc: 'Jeu d\'arcade de vol spatial' }
        }
    },
    {
        id: 'emotion-temp',
        name: '감정 온도계 테스트',
        shortDesc: '나의 감정 온도는 몇 도?',
        description: '10가지 질문으로 알아보는 나의 감정 온도! 16가지 유형 중 당신은? 결과 이미지 저장 & 공유.',
        icon: '🌡️',
        color: '#e07a5f',
        category: 'test',
        tags: ['심리테스트', '감정', '성격', '바이럴', 'HSP', '감정온도', 'emotion', 'test', 'personality', 'psychology'],
        url: 'https://dopabrain.com/emotion-temp/',
        isNew: true,
        isPopular: true,
        popularity: 8,
        i18n: {
            en: { name: 'Emotion Temperature', shortDesc: "What's your emotion temp?" },
            zh: { name: '情绪温度计测试', shortDesc: '你的情绪温度是几度？' },
            hi: { name: 'इमोशन टेम्परेचर', shortDesc: 'आपका भावना तापमान क्या है?' },
            ru: { name: 'Температура эмоций', shortDesc: 'Какова ваша эмоциональная t°?' },
            ja: { name: '感情温度計テスト', shortDesc: 'あなたの感情温度は何度？' },
            es: { name: 'Termómetro Emocional', shortDesc: '¿Cuál es tu temperatura emocional?' },
            pt: { name: 'Termômetro Emocional', shortDesc: 'Qual é sua temperatura emocional?' },
            id: { name: 'Tes Suhu Emosi', shortDesc: 'Berapa suhu emosimu?' },
            tr: { name: 'Duygu Termometresi', shortDesc: 'Duygu sıcaklığın kaç derece?' },
            de: { name: 'Emotionsthermometer', shortDesc: 'Wie hoch ist deine Gefühlstemperatur?' },
            fr: { name: 'Thermomètre Émotionnel', shortDesc: 'Quelle est votre température émotionnelle ?' }
        }
    },
    {
        id: 'mbti-love',
        name: 'MBTI 연애 궁합 테스트',
        shortDesc: '나의 연애 스타일은? 💕',
        description: '12가지 질문으로 알아보는 나의 MBTI 연애 스타일! 16가지 유형과 256가지 궁합표. 나와 찰떡궁합인 유형은?',
        icon: '💕',
        color: '#e74c3c',
        category: 'test',
        tags: ['MBTI', '연애', '궁합', '심리테스트', '연애스타일', 'love', 'romance', 'compatibility', 'dating', 'relationship'],
        url: 'https://dopabrain.com/mbti-love/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'MBTI Love Match', shortDesc: "What's your love style? 💕" },
            zh: { name: 'MBTI 恋爱配对', shortDesc: '你的恋爱风格是？💕' },
            hi: { name: 'MBTI लव मैच', shortDesc: 'आपकी प्रेम शैली क्या है? 💕' },
            ru: { name: 'MBTI совместимость', shortDesc: 'Какой ваш стиль любви? 💕' },
            ja: { name: 'MBTI 恋愛相性テスト', shortDesc: 'あなたの恋愛スタイルは？💕' },
            es: { name: 'Test de Amor MBTI', shortDesc: '¿Cuál es tu estilo de amor? 💕' },
            pt: { name: 'Teste de Amor MBTI', shortDesc: 'Qual é seu estilo de amor? 💕' },
            id: { name: 'Tes Cinta MBTI', shortDesc: 'Apa gaya cintamu? 💕' },
            tr: { name: 'MBTI Aşk Testi', shortDesc: 'Aşk tarzın ne? 💕' },
            de: { name: 'MBTI Liebes-Match', shortDesc: 'Was ist dein Liebesstil? 💕' },
            fr: { name: 'Test Amour MBTI', shortDesc: 'Quel est votre style amoureux ? 💕' }
        }
    },
    {
        id: 'hsp-test',
        name: 'HSP 민감성 테스트',
        shortDesc: '나는 고감수성자일까?',
        description: '20가지 질문으로 알아보는 HSP 민감도! 5가지 유형과 감각별 분석. 2026 메타센싱 트렌드.',
        icon: '🧠',
        color: '#7c3aed',
        category: 'test',
        tags: ['HSP', '민감성', '심리테스트', '메타센싱', '고감수성자', '감정', 'sensitivity', 'personality', 'test', 'psychology'],
        url: 'https://dopabrain.com/hsp-test/',
        isNew: true,
        isPopular: true,
        popularity: 8,
        i18n: {
            en: { name: 'HSP Sensitivity Test', shortDesc: 'Are you highly sensitive?' },
            zh: { name: 'HSP 敏感度测试', shortDesc: '你是高敏感人群吗？' },
            hi: { name: 'HSP संवेदनशीलता परीक्षण', shortDesc: 'क्या आप अति संवेदनशील हैं?' },
            ru: { name: 'Тест HSP', shortDesc: 'Вы высокочувствительный человек?' },
            ja: { name: 'HSP 感受性テスト', shortDesc: 'あなたは繊細さん？' },
            es: { name: 'Test de Sensibilidad HSP', shortDesc: '¿Eres altamente sensible?' },
            pt: { name: 'Teste de Sensibilidade HSP', shortDesc: 'Você é altamente sensível?' },
            id: { name: 'Tes Sensitivitas HSP', shortDesc: 'Apakah kamu sangat sensitif?' },
            tr: { name: 'HSP Hassasiyet Testi', shortDesc: 'Yüksek hassasiyetli misin?' },
            de: { name: 'HSP-Sensibilitätstest', shortDesc: 'Bist du hochsensibel?' },
            fr: { name: 'Test de Sensibilité HSP', shortDesc: 'Êtes-vous hypersensible ?' }
        }
    },
    {
        id: 'love-frequency',
        name: '사랑 주파수 테스트',
        shortDesc: '나의 사랑은 몇 Hz?',
        description: '솔페지오 주파수 기반 사랑 유형 테스트! 10문항으로 나의 사랑 주파수를 찾고 실제 주파수 음악도 들어보세요.',
        icon: '💕',
        color: '#e91e63',
        category: 'fortune',
        tags: ['사랑', '주파수', '연애', '심리테스트', '솔페지오', '528Hz', '궁합', 'love', 'frequency', 'music', 'solfeggio', 'healing'],
        url: 'https://dopabrain.com/love-frequency/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Love Frequency Test', shortDesc: 'What Hz is your love?' },
            zh: { name: '爱情频率测试', shortDesc: '你的爱情是几Hz？' },
            hi: { name: 'लव फ्रीक्वेंसी टेस्ट', shortDesc: 'आपके प्यार की फ्रीक्वेंसी?' },
            ru: { name: 'Частота любви', shortDesc: 'На какой частоте ваша любовь?' },
            ja: { name: '愛の周波数テスト', shortDesc: 'あなたの愛は何Hz？' },
            es: { name: 'Test de Frecuencia del Amor', shortDesc: '¿A qué frecuencia está tu amor?' },
            pt: { name: 'Teste de Frequência do Amor', shortDesc: 'Qual a frequência do seu amor?' },
            id: { name: 'Tes Frekuensi Cinta', shortDesc: 'Berapa Hz cintamu?' },
            tr: { name: 'Aşk Frekansı Testi', shortDesc: 'Aşkın kaç Hz?' },
            de: { name: 'Liebesfrequenz-Test', shortDesc: 'Auf welcher Frequenz ist deine Liebe?' },
            fr: { name: 'Test Fréquence d\'Amour', shortDesc: 'À quelle fréquence vibre votre amour ?' }
        }
    },
    {
        id: 'stack-tower',
        name: 'Stack Tower',
        shortDesc: '타이밍 블록 쌓기 게임',
        description: '완벽한 타이밍으로 블록을 쌓아 하늘 끝까지! 5가지 테마와 20개 칭호에 도전하세요.',
        icon: '🏗️',
        color: '#f59e0b',
        category: 'game',
        tags: ['게임', '아케이드', '타이밍', '블록', '캐주얼', '타워', 'game', 'arcade', 'stacking', 'puzzle', 'casual'],
        url: 'https://dopabrain.com/stack-tower/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Stack Tower', shortDesc: 'Timing block stacking game' },
            zh: { name: 'Stack Tower', shortDesc: '计时堆叠方块游戏' },
            hi: { name: 'Stack Tower', shortDesc: 'टाइमिंग ब्लॉक स्टैकिंग गेम' },
            ru: { name: 'Stack Tower', shortDesc: 'Игра с укладкой блоков' },
            ja: { name: 'Stack Tower', shortDesc: 'タイミングブロック積みゲーム' },
            es: { name: 'Stack Tower', shortDesc: 'Juego de apilar bloques' },
            pt: { name: 'Stack Tower', shortDesc: 'Jogo de empilhar blocos' },
            id: { name: 'Stack Tower', shortDesc: 'Game menumpuk blok' },
            tr: { name: 'Stack Tower', shortDesc: 'Zamanlama blok istif oyunu' },
            de: { name: 'Stack Tower', shortDesc: 'Timing-Blockstapelspiel' },
            fr: { name: 'Stack Tower', shortDesc: 'Jeu d\'empilement de blocs' }
        }
    },
    {
        id: 'kpop-position',
        name: 'K-POP 포지션 테스트',
        shortDesc: '나의 아이돌 포지션은?',
        description: '12가지 질문으로 알아보는 나의 K-POP 포지션! 메인보컬, 리더, 래퍼, 댄서, 비주얼, 막내, 올라운더 중 당신은?',
        icon: '🎤',
        color: '#ff2d78',
        category: 'test',
        tags: ['KPOP', '포지션', '아이돌', '심리테스트', 'BTS', 'BLACKPINK', 'kpop', 'idol', 'music', 'singer', 'test'],
        url: 'https://dopabrain.com/kpop-position/',
        isNew: true,
        isPopular: true,
        popularity: 6,
        i18n: {
            en: { name: 'K-POP Position Test', shortDesc: "What's your idol position?" },
            zh: { name: 'K-POP 位置测试', shortDesc: '你的偶像位置是？' },
            hi: { name: 'K-POP पोजीशन टेस्ट', shortDesc: 'आपकी आइडल पोजीशन क्या है?' },
            ru: { name: 'K-POP позиция', shortDesc: 'Какая ваша позиция в группе?' },
            ja: { name: 'K-POP ポジションテスト', shortDesc: 'あなたのアイドルポジションは？' },
            es: { name: 'Test de Posición K-POP', shortDesc: '¿Cuál es tu posición de idol?' },
            pt: { name: 'Teste de Posição K-POP', shortDesc: 'Qual é sua posição de idol?' },
            id: { name: 'Tes Posisi K-POP', shortDesc: 'Apa posisi idolmu?' },
            tr: { name: 'K-POP Pozisyon Testi', shortDesc: 'İdol pozisyonun ne?' },
            de: { name: 'K-POP Positionstest', shortDesc: 'Was ist deine Idol-Position?' },
            fr: { name: 'Test Position K-POP', shortDesc: 'Quelle est votre position d\'idol ?' }
        }
    },
    {
        id: 'emoji-merge',
        name: '이모지 머지',
        shortDesc: '이모지 진화 퍼즐 게임',
        description: '같은 이모지를 합쳐 진화시키세요! 🥚→🐣→🐥→🦅→🐉→👑 알에서 용까지! 씨앗→세계수, 물방울→은하 4가지 진화 체인.',
        icon: '🧬',
        color: '#f97316',
        category: 'game',
        tags: ['이모지', '머지', '진화', '퍼즐', '게임', '2048', '캐주얼', 'emoji', 'merge', 'puzzle', 'game', 'casual'],
        url: 'https://dopabrain.com/emoji-merge/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Emoji Merge', shortDesc: 'Emoji evolution puzzle game' },
            zh: { name: 'Emoji 合并', shortDesc: 'Emoji 进化益智游戏' },
            hi: { name: 'Emoji Merge', shortDesc: 'इमोजी इवोल्यूशन पज़ल गेम' },
            ru: { name: 'Emoji Merge', shortDesc: 'Головоломка с эмодзи' },
            ja: { name: 'Emoji Merge', shortDesc: '絵文字進化パズルゲーム' },
            es: { name: 'Emoji Merge', shortDesc: 'Juego de puzle con emojis' },
            pt: { name: 'Emoji Merge', shortDesc: 'Jogo de puzzle de emojis' },
            id: { name: 'Emoji Merge', shortDesc: 'Game puzzle evolusi emoji' },
            tr: { name: 'Emoji Merge', shortDesc: 'Emoji evrim bulmaca oyunu' },
            de: { name: 'Emoji Merge', shortDesc: 'Emoji-Evolutions-Puzzle' },
            fr: { name: 'Emoji Merge', shortDesc: 'Jeu de puzzle d\'émojis' }
        }
    },
    {
        id: 'zigzag-runner',
        name: 'Zigzag Runner',
        shortDesc: '방향 전환 아케이드 게임',
        description: '탭 한 번으로 방향 전환! 끝없는 지그재그 길 위에서 코인을 모으며 달리세요. 5가지 테마와 20개 칭호.',
        icon: '🏃',
        color: '#10b981',
        category: 'game',
        tags: ['게임', '아케이드', '지그재그', '러너', '캐주얼', '원탭', 'game', 'arcade', 'runner', 'casual', 'tap'],
        url: 'https://dopabrain.com/zigzag-runner/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Zigzag Runner', shortDesc: 'Direction-switching arcade' },
            zh: { name: 'Zigzag Runner', shortDesc: '方向切换街机游戏' },
            hi: { name: 'Zigzag Runner', shortDesc: 'दिशा बदलने वाला आर्केड गेम' },
            ru: { name: 'Zigzag Runner', shortDesc: 'Аркада со сменой направления' },
            ja: { name: 'Zigzag Runner', shortDesc: '方向転換アーケードゲーム' },
            es: { name: 'Zigzag Runner', shortDesc: 'Arcade de cambio de dirección' },
            pt: { name: 'Zigzag Runner', shortDesc: 'Arcade de mudança de direção' },
            id: { name: 'Zigzag Runner', shortDesc: 'Game arkade ganti arah' },
            tr: { name: 'Zigzag Runner', shortDesc: 'Yön değiştirme arcade oyunu' },
            de: { name: 'Zigzag Runner', shortDesc: 'Richtungswechsel-Arcade' },
            fr: { name: 'Zigzag Runner', shortDesc: 'Arcade de changement de direction' }
        }
    },
    {
        id: 'past-life',
        name: '전생 직업 테스트',
        shortDesc: '나의 전생은 무엇이었을까?',
        description: '10문항으로 알아보는 나의 전생 직업! 기사단장, 해적 선장, 르네상스 화가... 8가지 전생 유형과 궁합까지.',
        icon: '🗡️',
        color: '#C9A96E',
        category: 'fortune',
        tags: ['전생', '심리테스트', '바이럴', '궁합', '전생직업', 'pastlife', 'reincarnation', 'test', 'personality', 'viral'],
        url: 'https://dopabrain.com/past-life/',
        isNew: true,
        isPopular: true,
        popularity: 9,
        i18n: {
            en: { name: 'Past Life Job Test', shortDesc: 'What was your past life?' },
            zh: { name: '前世职业测试', shortDesc: '你的前世是什么？' },
            hi: { name: 'पूर्वजन्म परीक्षण', shortDesc: 'आपका पूर्वजन्म क्या था?' },
            ru: { name: 'Тест прошлой жизни', shortDesc: 'Кем вы были в прошлой жизни?' },
            ja: { name: '前世の職業テスト', shortDesc: 'あなたの前世は何だった？' },
            es: { name: 'Test de Vida Pasada', shortDesc: '¿Qué fuiste en tu vida pasada?' },
            pt: { name: 'Teste de Vida Passada', shortDesc: 'O que você foi na vida passada?' },
            id: { name: 'Tes Kehidupan Lampau', shortDesc: 'Apa pekerjaan masa lalumu?' },
            tr: { name: 'Geçmiş Yaşam Testi', shortDesc: 'Geçmiş yaşamınızda neydiniz?' },
            de: { name: 'Früheres-Leben-Test', shortDesc: 'Was warst du in einem früheren Leben?' },
            fr: { name: 'Test de Vie Antérieure', shortDesc: 'Qu\'étiez-vous dans une vie passée ?' }
        }
    },
    {
        id: 'idle-clicker',
        name: '던전 클리커',
        shortDesc: '방치형 RPG 던전 탐험 게임',
        description: '던전에서 몬스터를 무찌르고 강력한 장비를 장착하세요! 나무 검에서 영웅의 검까지 10단계 장비 수집.',
        icon: '⚔️',
        color: '#8b5cf6',
        category: 'game',
        tags: ['게임', '클리커', '방치형', 'RPG', '던전', '캐주얼', 'game', 'idle', 'clicker', 'rpg', 'adventure'],
        url: 'https://dopabrain.com/idle-clicker/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Dungeon Clicker', shortDesc: 'Idle RPG dungeon game' },
            zh: { name: '地牢点击者', shortDesc: '放置型RPG地牢游戏' },
            hi: { name: 'डंजन क्लिकर', shortDesc: 'आइडल RPG डंजन गेम' },
            ru: { name: 'Данжен Кликер', shortDesc: 'Idle RPG подземелье' },
            ja: { name: 'ダンジョンクリッカー', shortDesc: '放置型RPGダンジョンゲーム' },
            es: { name: 'Dungeon Clicker', shortDesc: 'Juego idle RPG de mazmorras' },
            pt: { name: 'Dungeon Clicker', shortDesc: 'Jogo idle RPG de masmorra' },
            id: { name: 'Dungeon Clicker', shortDesc: 'Game RPG idle dungeon' },
            tr: { name: 'Dungeon Clicker', shortDesc: 'Idle RPG zindan oyunu' },
            de: { name: 'Dungeon Clicker', shortDesc: 'Idle-RPG-Dungeon-Spiel' },
            fr: { name: 'Dungeon Clicker', shortDesc: 'Jeu RPG idle de donjon' }
        }
    },
    {
        id: 'valentine',
        name: '밸런타인 궁합 테스트',
        shortDesc: '우리의 궁합은 몇 %?',
        description: '이름+생일+5가지 질문으로 알아보는 밸런타인 궁합! 이름 획수 궁합, 별자리 궁합, 사랑 유형까지 완벽 분석.',
        icon: '💕',
        color: '#ff4b91',
        category: 'fortune',
        tags: ['밸런타인', '궁합', '커플', '연애', '사랑', '심리테스트', 'valentine', 'love', 'compatibility', 'couple', 'matching'],
        url: 'https://dopabrain.com/valentine/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Valentine Match Test', shortDesc: 'How compatible are you? %' },
            zh: { name: '情人节配对测试', shortDesc: '你们的匹配度是几%？' },
            hi: { name: 'वैलेंटाइन मैच टेस्ट', shortDesc: 'आपकी जोड़ी कितनी परफेक्ट? %' },
            ru: { name: 'Тест совместимости', shortDesc: 'Какова ваша совместимость? %' },
            ja: { name: 'バレンタイン相性テスト', shortDesc: '二人の相性は何%？' },
            es: { name: 'Test de San Valentín', shortDesc: '¿Cuánto son compatibles? %' },
            pt: { name: 'Teste de Dia dos Namorados', shortDesc: 'Quão compatíveis vocês são? %' },
            id: { name: 'Tes Kecocokan Valentine', shortDesc: 'Seberapa cocok kalian? %' },
            tr: { name: 'Sevgililer Günü Testi', shortDesc: 'Ne kadar uyumlusunuz? %' },
            de: { name: 'Valentinstag-Match-Test', shortDesc: 'Wie kompatibel seid ihr? %' },
            fr: { name: 'Test Saint-Valentin', shortDesc: 'Êtes-vous compatibles ? %' }
        }
    },
    {
        id: 'brain-type',
        name: '두뇌 유형 테스트',
        shortDesc: '나의 두뇌는 어떤 유형?',
        description: '10개 질문으로 당신의 뇌 유형을 분석합니다. 8가지 두뇌 유형 중 당신을 가장 잘 나타내는 유형을 발견해보세요!',
        icon: '🧠',
        color: '#e040fb',
        category: 'test',
        tags: ['뇌', '성격', '심리테스트', '진단', '분석', 'brain', 'test', 'personality', 'psychology', 'mindtype'],
        url: 'https://dopabrain.com/brain-type/',
        isNew: true,
        isPopular: false,
        popularity: 7,
        i18n: {
            en: { name: 'Brain Type Test', shortDesc: 'What is your brain type?' },
            zh: { name: '脑型测试', shortDesc: '你的大脑类型是什么？' },
            hi: { name: 'ब्रेन टाइप टेस्ट', shortDesc: 'आपका मस्तिष्क प्रकार क्या है?' },
            ru: { name: 'Тест типа мозга', shortDesc: 'Какой у вас тип мозга?' },
            ja: { name: '脳型診断テスト', shortDesc: 'あなたの脳型は?' },
            es: { name: 'Test de Tipo de Cerebro', shortDesc: '¿Cuál es tu tipo de cerebro?' },
            pt: { name: 'Teste de Tipo Cerebral', shortDesc: 'Qual é o seu tipo de cérebro?' },
            id: { name: 'Tes Tipe Otak', shortDesc: 'Apa tipe otak Anda?' },
            tr: { name: 'Beyin Tipi Testi', shortDesc: 'Beyin tipiniz nedir?' },
            de: { name: 'Gehirn-Typ-Test', shortDesc: 'Welcher Gehirntyp sind Sie?' },
            fr: { name: 'Test de Type de Cerveau', shortDesc: 'Quel est votre type de cerveau?' }
        }
    },
    {
        id: 'typing-speed',
        name: '타이핑 속도 테스트',
        shortDesc: 'WPM 측정 게임',
        description: '타이핑 속도를 측정하세요! WPM(분당 단어수)과 정확도를 테스트하고 당신의 타이핑 실력을 확인하세요. 2가지 모드: 단어 모드, 문장 모드.',
        icon: '⌨️',
        color: '#4CAF50',
        category: 'brain',
        tags: ['타이핑', '게임', '속도테스트', 'WPM', '연습', 'typing', 'speed', 'test', 'game', 'keyboard'],
        url: 'https://dopabrain.com/typing-speed/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Typing Speed Test', shortDesc: 'WPM measurement game' },
            zh: { name: '打字速度测试', shortDesc: 'WPM测量游戏' },
            hi: { name: 'टाइपिंग स्पीड टेस्ट', shortDesc: 'WPM माप गेम' },
            ru: { name: 'Тест скорости печати', shortDesc: 'Игра измерения WPM' },
            ja: { name: 'タイピング速度テスト', shortDesc: 'WPM測定ゲーム' },
            es: { name: 'Prueba de Velocidad de Escritura', shortDesc: 'Juego de medición WPM' },
            pt: { name: 'Teste de Velocidade de Digitação', shortDesc: 'Jogo de medição WPM' },
            id: { name: 'Tes Kecepatan Mengetik', shortDesc: 'Game pengukuran WPM' },
            tr: { name: 'Yazma Hızı Testi', shortDesc: 'WPM ölçüm oyunu' },
            de: { name: 'Schreibgeschwindigkeitstest', shortDesc: 'WPM-Messspiel' },
            fr: { name: 'Test de Vitesse de Saisie', shortDesc: 'Jeu de mesure WPM' }
        }
    },
    {
        id: 'color-memory',
        name: '색상 기억력',
        shortDesc: '기억력 도전 게임',
        description: '색상의 순서를 따라 기억하는 Simon Says 스타일의 중독성 있는 게임. 레벨이 높아질수록 속도가 빨라집니다!',
        icon: '🎨',
        color: '#FF6B6B',
        category: 'brain',
        tags: ['게임', '기억력', '색상', '두뇌', '캐주얼', '중독성', 'game', 'memory', 'color', 'puzzle', 'brain'],
        url: 'https://dopabrain.com/color-memory/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Color Memory', shortDesc: 'Memory challenge game' },
            zh: { name: '色彩记忆', shortDesc: '记忆力挑战游戏' },
            hi: { name: 'रंग मेमोरी', shortDesc: 'स्मृति चुनौती गेम' },
            ru: { name: 'Цветная Память', shortDesc: 'Игра на память' },
            ja: { name: 'カラーメモリー', shortDesc: 'メモリー挑戦ゲーム' },
            es: { name: 'Memoria de Colores', shortDesc: 'Juego de desafío de memoria' },
            pt: { name: 'Memória de Cores', shortDesc: 'Jogo de desafio de memória' },
            id: { name: 'Memori Warna', shortDesc: 'Game tantangan memori' },
            tr: { name: 'Renk Belleği', shortDesc: 'Bellek mücadelesi oyunu' },
            de: { name: 'Farbgedächtnis', shortDesc: 'Gedächtnisherausforderungsspiel' },
            fr: { name: 'Mémoire des Couleurs', shortDesc: 'Jeu de défi mémoire' }
        }
    },
    {
        id: 'word-scramble',
        name: '단어 스크램블',
        shortDesc: '뒤섞인 글자 맞추기 게임',
        description: '뒤섞인 알파벳을 올바른 순서로 배치하는 단어 퍼즐 게임! 난이도별 도전, 점수 경쟁, 콤보 시스템, 무한 플레이 가능!',
        icon: '🎮',
        color: '#e056fd',
        category: 'brain',
        tags: ['게임', '퍼즐', '단어', '영어', '뇌훈련', 'game', 'word', 'puzzle', 'vocabulary', 'brain'],
        url: 'https://dopabrain.com/word-scramble/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Word Scramble', shortDesc: 'Unscramble word puzzle game' },
            zh: { name: '单词乱序游戏', shortDesc: '解开打乱的字母' },
            hi: { name: 'शब्द स्क्रैम्बल', shortDesc: 'शब्द पहेली खेल' },
            ru: { name: 'Word Scramble', shortDesc: 'Игра со словами' },
            ja: { name: 'Word Scramble', shortDesc: 'しりとり単語ゲーム' },
            es: { name: 'Word Scramble', shortDesc: 'Juego de palabras revueltas' },
            pt: { name: 'Word Scramble', shortDesc: 'Jogo de palavras embaralhadas' },
            id: { name: 'Word Scramble', shortDesc: 'Game kata diacak' },
            tr: { name: 'Word Scramble', shortDesc: 'Kelime karıştırma oyunu' },
            de: { name: 'Word Scramble', shortDesc: 'Wort-Puzzle-Spiel' },
            fr: { name: 'Word Scramble', shortDesc: 'Jeu de mots mélangés' }
        }
    },
    {
        id: 'number-puzzle',
        name: '숫자 퍼즐 2048',
        shortDesc: '2048 숫자 게임',
        description: '같은 숫자를 합쳐 2048을 만드는 퍼즐 게임! 전략적 사고와 두뇌 활동을 자극하는 중독성 있는 게임.',
        icon: '🔢',
        color: '#EDB879',
        category: 'brain',
        tags: ['게임', '퍼즐', '숫자', '2048', '캐주얼', 'game', 'puzzle', '2048', 'number', 'math'],
        url: 'https://dopabrain.com/number-puzzle/',
        isNew: true,
        isPopular: false,
        popularity: 5,
        i18n: {
            en: { name: 'Number Puzzle 2048', shortDesc: '2048 number game' },
            zh: { name: '数字拼图2048', shortDesc: '2048数字游戏' },
            hi: { name: 'संख्या पहेली 2048', shortDesc: '2048 नंबर गेम' },
            ru: { name: 'Числовая Головоломка 2048', shortDesc: 'Числовая игра 2048' },
            ja: { name: 'ナンバーパズル2048', shortDesc: '2048数字ゲーム' },
            es: { name: 'Puzzle de Números 2048', shortDesc: 'Juego de números 2048' },
            pt: { name: 'Puzzle de Números 2048', shortDesc: 'Jogo de números 2048' },
            id: { name: 'Puzzle Angka 2048', shortDesc: 'Game angka 2048' },
            tr: { name: 'Sayı Bulmacası 2048', shortDesc: '2048 sayı oyunu' },
            de: { name: 'Zahlen-Puzzle 2048', shortDesc: 'Zahlenpuzzle-Spiel' },
            fr: { name: 'Puzzle de Nombres 2048', shortDesc: 'Jeu de nombres 2048' }
        }
    },
    {
        id: 'memory-card',
        name: '메모리 카드 플립',
        shortDesc: '카드 뒤집기 기억력 게임',
        description: '카드를 뒤집어서 짝을 맞추는 클래식 메모리 게임! 콤보 시스템과 다양한 테마로 더욱 재미있는 게임 경험을 즐기세요. 4가지 테마 & 3가지 난이도!',
        icon: '🎴',
        color: '#e67e22',
        category: 'brain',
        tags: ['게임', '기억력', '카드', '콤보', '캐주얼', 'memory', 'card', 'flip', 'game', 'puzzle'],
        url: 'https://dopabrain.com/memory-card/',
        isNew: true,
        isPopular: true,
        popularity: 7,
        i18n: {
            en: { name: 'Memory Card Flip', shortDesc: 'Card flipping memory game' },
            zh: { name: '记忆卡翻转', shortDesc: '卡牌翻转记忆游戏' },
            hi: { name: 'मेमोरी कार्ड फ्लिप', shortDesc: 'कार्ड फ्लिपिंग स्मृति खेल' },
            ru: { name: 'Перекидывание карт памяти', shortDesc: 'Игра на память с переворотом карт' },
            ja: { name: 'メモリーカードフリップ', shortDesc: 'カードめくり記憶ゲーム' },
            es: { name: 'Memory Card Flip', shortDesc: 'Juego de memoria de volteo de cartas' },
            pt: { name: 'Memory Card Flip', shortDesc: 'Jogo de memória com virada de cartas' },
            id: { name: 'Memory Card Flip', shortDesc: 'Game memori dengan kartu yang dibalik' },
            tr: { name: 'Memory Card Flip', shortDesc: 'Kart çevirme hafıza oyunu' },
            de: { name: 'Memory Card Flip', shortDesc: 'Kartenkipp-Gedächtnisspiel' },
            fr: { name: 'Memory Card Flip', shortDesc: 'Jeu de mémoire avec retournement de cartes' }
        }
    },
    {
        id: 'stress-check',
        name: '스트레스 레벨 체크',
        shortDesc: '당신의 스트레스 측정하기',
        description: '15개 질문으로 직장, 인간관계, 건강, 재정, 일상의 스트레스 레벨을 측정하고 맞춤형 해소법을 받으세요! 카테고리별 분석, AI 심층 분석, 결과 이미지 저장 & 공유.',
        icon: '😰',
        color: '#e74c3c',
        category: 'test',
        tags: ['스트레스', '심리테스트', '감정', '건강', '분석', '테스트', 'stress', 'test', 'mental', 'health', 'psychology', 'emotion'],
        url: 'https://dopabrain.com/stress-check/',
        isNew: false,
        isPopular: true,
        popularity: 6,
        i18n: {
            en: { name: 'Stress Level Check', shortDesc: 'Measure your stress level' },
            zh: { name: '压力水平检查', shortDesc: '测量您的压力水平' },
            hi: { name: 'स्ट्रेस स्तर जांच', shortDesc: 'अपने तनाव को मापें' },
            ru: { name: 'Проверка уровня стресса', shortDesc: 'Измерьте уровень стресса' },
            ja: { name: 'ストレスレベルチェック', shortDesc: 'あなたの ストレスレベルを測定' },
            es: { name: 'Comprobador de Nivel de Estrés', shortDesc: 'Mide tu nivel de estrés' },
            pt: { name: 'Verificador de Nível de Estresse', shortDesc: 'Meça seu nível de estresse' },
            id: { name: 'Pemeriksa Tingkat Stres', shortDesc: 'Ukur tingkat stres Anda' },
            tr: { name: 'Stres Seviyesi Kontrolü', shortDesc: 'Stres seviyenizi ölçün' },
            de: { name: 'Stressabbau-Check', shortDesc: 'Messen Sie Ihren Stresslevel' },
            fr: { name: 'Vérificateur de Niveau de Stress', shortDesc: 'Mesurez votre niveau de stress' }
        }
    },
    {
        id: 'snake-game',
        name: 'Snake Classic 🐍',
        shortDesc: '클래식 뱀 게임 현대적 리메이크',
        description: '네온 스타일의 클래식 뱀 게임! 모바일 스와이프, 데스크톱 키보드, 무한모드/벽모드, 파티클 이펙트, 음향 효과. 최고 점수를 목표로 도전하세요!',
        icon: '🐍',
        color: '#2ecc71',
        category: 'game',
        tags: ['게임', '뱀', '클래식', '아케이드', '캐주얼', '네온', 'snake', 'game', 'arcade', 'classic', 'casual'],
        url: 'https://dopabrain.com/snake-game/',
        isNew: true,
        isPopular: true,
        popularity: 5,
        i18n: {
            en: { name: 'Snake Classic', shortDesc: 'Modern remake of classic snake game' },
            zh: { name: 'Snake Classic 🐍', shortDesc: '经典贪吃蛇游戏现代重制版' },
            hi: { name: 'Snake Classic 🐍', shortDesc: 'क्लासिक सांप खेल का आधुनिक रीमेक' },
            ru: { name: 'Snake Classic 🐍', shortDesc: 'Современный ремейк классической игры' },
            ja: { name: 'Snake Classic 🐍', shortDesc: 'クラシックヘビゲームの現代的リメイク' },
            es: { name: 'Snake Classic 🐍', shortDesc: 'Juego de serpiente clásico remasterizado' },
            pt: { name: 'Snake Classic 🐍', shortDesc: 'Reedição moderna do clássico jogo de cobra' },
            id: { name: 'Snake Classic 🐍', shortDesc: 'Remake modern dari permainan ular klasik' },
            tr: { name: 'Snake Classic 🐍', shortDesc: 'Klasik yılan oyununun modern yeniden yapısı' },
            de: { name: 'Snake Classic 🐍', shortDesc: 'Modernes Remake des klassischen Schlangenspiels' },
            fr: { name: 'Snake Classic 🐍', shortDesc: 'Remake moderne du jeu de serpent classique' }
        }
    },
    {
        id: 'bmi-calculator',
        name: 'BMI 계산기',
        shortDesc: '체질량지수 계산 & 건강 분석',
        description: '키와 몸무게를 입력하면 즉시 BMI 체질량지수를 계산하고 건강 상태를 분석합니다. 게이지 시각화, 이상적 체중 범위, 맞춤형 건강 팁. 히스토리 저장 기능.',
        icon: '💪',
        color: '#00b894',
        category: 'tool',
        tags: ['BMI', '계산기', '체질량지수', '건강', '피트니스', '체중관리', 'calculator', 'health', 'fitness', 'weight', 'wellness'],
        url: 'https://dopabrain.com/bmi-calculator/',
        isNew: false,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'BMI Calculator', shortDesc: 'BMI & health analysis' },
            zh: { name: 'BMI 计算器', shortDesc: '体质指数计算与健康分析' },
            hi: { name: 'BMI कैलकुलेटर', shortDesc: 'BMI और स्वास्थ्य विश्लेषण' },
            ru: { name: 'Калькулятор BMI', shortDesc: 'BMI и анализ здоровья' },
            ja: { name: 'BMI計算機', shortDesc: 'BMI と健康分析' },
            es: { name: 'Calculadora BMI', shortDesc: 'Cálculo de IMC y análisis de salud' },
            pt: { name: 'Calculadora IMC', shortDesc: 'Cálculo de IMC e análise de saúde' },
            id: { name: 'Kalkulator BMI', shortDesc: 'Perhitungan BMI dan analisis kesehatan' },
            tr: { name: 'BMI Hesaplayıcı', shortDesc: 'BMI hesaplaması ve sağlık analizi' },
            de: { name: 'BMI-Rechner', shortDesc: 'BMI-Berechnung und Gesundheitsanalyse' },
            fr: { name: 'Calculatrice BMI', shortDesc: 'Calcul IMC et analyse de santé' }
        }
    },
    {
        id: 'block-puzzle',
        name: 'Block Puzzle',
        shortDesc: '클래식 블록 퍼즐 게임',
        description: '재미있는 클래식 블록 퍼즐 게임! 떨어지는 블록을 배치하여 줄을 완성하세요. 레벨 시스템, 콤보, 하드드롭, 홀드 기능. 네온 블록과 음향 효과가 있는 중독성 있는 게임!',
        icon: '🧩',
        color: '#9b59b6',
        category: 'game',
        tags: ['블록 퍼즐', '테트리스', '캐주얼 게임', '무료 게임', '퍼즐 게임', 'block', 'puzzle', 'tetris', 'casual', 'game', 'arcade'],
        url: 'https://dopabrain.com/block-puzzle/',
        isNew: true,
        isPopular: true,
        popularity: 5,
        i18n: {
            en: { name: 'Block Puzzle', shortDesc: 'Classic block puzzle game' },
            zh: { name: '方块拼图', shortDesc: '经典方块拼图游戏' },
            hi: { name: 'ब्लॉक पहेली', shortDesc: 'क्लासिक ब्लॉक पहेली गेम' },
            ru: { name: 'Блок-Пазл', shortDesc: 'Классическая игра пазл' },
            ja: { name: 'ブロックパズル', shortDesc: 'クラシックブロックパズル' },
            es: { name: 'Block Puzzle', shortDesc: 'Juego de puzzle de bloques clásico' },
            pt: { name: 'Block Puzzle', shortDesc: 'Clássico jogo de puzzle de blocos' },
            id: { name: 'Block Puzzle', shortDesc: 'Game puzzle blok klasik' },
            tr: { name: 'Block Puzzle', shortDesc: 'Klasik blok bulmaca oyunu' },
            de: { name: 'Block Puzzle', shortDesc: 'Klassisches Blockpuzzle-Spiel' },
            fr: { name: 'Block Puzzle', shortDesc: 'Jeu de puzzle de blocs classique' }
        }
    },
    {
        id: 'qr-generator',
        name: 'QR 코드 생성기',
        shortDesc: 'URL·텍스트·WiFi·연락처 QR 변환',
        description: '고급 QR 코드 생성 도구. URL, 텍스트, WiFi, 연락처, 이메일, 전화번호를 QR 코드로 변환하세요. 색상 커스터마이징, 사이즈 조절, PNG 다운로드 기능 제공.',
        icon: '🔲',
        color: '#1abc9c',
        category: 'tool',
        tags: ['QR 코드', '생성기', 'QR', 'URL', 'WiFi', '연락처', '바코드', 'qr', 'code', 'generator', 'barcode'],
        url: 'https://dopabrain.com/qr-generator/',
        isNew: true,
        isPopular: false,
        popularity: 4,
        i18n: {
            en: { name: 'QR Code Generator', shortDesc: 'Convert URL·text·WiFi·contact to QR' },
            zh: { name: '二维码生成器', shortDesc: '将URL·文本·WiFi·联系人转换为二维码' },
            hi: { name: 'QR कोड जनरेटर', shortDesc: 'URL·पाठ·WiFi·संपर्क को QR में परिवर्तित करें' },
            ru: { name: 'Генератор QR-кодов', shortDesc: 'Преобразуйте URL·текст·WiFi·контакт в QR' },
            ja: { name: 'QRコード生成器', shortDesc: 'URL·テキスト·WiFi·連絡先をQRに変換' },
            es: { name: 'Generador de Códigos QR', shortDesc: 'Convertir URL·texto·WiFi·contacto a QR' },
            pt: { name: 'Gerador de Código QR', shortDesc: 'Converta URL·texto·WiFi·contato em QR' },
            id: { name: 'Generator Kode QR', shortDesc: 'Konversi URL·teks·WiFi·kontak ke QR' },
            tr: { name: 'QR Kod Oluşturucu', shortDesc: 'URL·metin·WiFi·iletişimi QR\'ye dönüştürün' },
            de: { name: 'QR-Code-Generator', shortDesc: 'URL·Text·WiFi·Kontakt in QR konvertieren' },
            fr: { name: 'Générateur de Code QR', shortDesc: 'Convertir URL·texte·WiFi·contact en QR' }
        }
    },
    {
        id: 'numerology',
        name: '운명의 숫자 수비학',
        shortDesc: '인생 경로 숫자 & 궁합',
        description: '생년월일로 인생 경로 숫자를 계산하고 이름으로 표현 숫자를 알아보세요. 마스터 넘버 해석, 숫자 궁합, AI 심층 분석. SNS 공유 최적화!',
        icon: '🔢',
        color: '#f1c40f',
        category: 'fortune',
        tags: ['수비학', '운명', '숫자', '인생경로', '표현숫자', '마스터넘버', '궁합', 'numerology', 'destiny', 'number', 'lifepath'],
        url: 'https://dopabrain.com/numerology/',
        isNew: false,
        isPopular: true,
        popularity: 6,
        i18n: {
            en: { name: 'Numerology - Destiny Numbers', shortDesc: 'Life path & compatibility' },
            zh: { name: '数字命理学 - 命运之数', shortDesc: '人生路径和兼容性' },
            hi: { name: 'संख्या विज्ञान - भाग्य संख्या', shortDesc: 'जीवन पथ और संगतता' },
            ru: { name: 'Нумерология - Числа Судьбы', shortDesc: 'Путь жизни и совместимость' },
            ja: { name: '数秘術 - 運命の数字', shortDesc: '人生経路と相性' },
            es: { name: 'Numerología - Números del Destino', shortDesc: 'Camino de vida y compatibilidad' },
            pt: { name: 'Numerologia - Números do Destino', shortDesc: 'Caminho de vida e compatibilidade' },
            id: { name: 'Numerologi - Angka Takdir', shortDesc: 'Jalan hidup dan kompatibilitas' },
            tr: { name: 'Numeroloji - Kader Sayıları', shortDesc: 'Yaşam yolu ve uyumluluk' },
            de: { name: 'Numerologie - Schicksalszahlen', shortDesc: 'Lebensweg und Kompatibilität' },
            fr: { name: 'Numérologie - Nombres du Destin', shortDesc: 'Chemin de vie et compatibilité' }
        }
    },
    {
        id: 'future-self',
        name: '10년 후의 나',
        shortDesc: '미래 자아 발견 테스트',
        description: '현재의 습관과 성격으로 10년 뒤 당신의 미래 자아를 예측합니다. CEO, 예술가, 모험가, 학자, 힐러, 인플루언서, 발명가, 자유인 중 누구인가요? SNS 공유 최적화!',
        icon: '🚀',
        color: '#3498db',
        category: 'test',
        tags: ['성격테스트', '미래예측', '자아발견', '타입테스트', '심리테스트', '인생테스트', 'future', 'self', 'personality', 'prediction', 'archetype'],
        url: 'https://dopabrain.com/future-self/',
        isNew: true,
        isPopular: true,
        popularity: 8,
        i18n: {
            en: { name: '10 Years From Now', shortDesc: 'Discover your future archetype' },
            zh: { name: '10年后的你', shortDesc: '发现你的未来自我' },
            hi: { name: '10 साल बाद', shortDesc: 'अपने भविष्य की खोज करें' },
            ru: { name: '10 лет спустя', shortDesc: 'Откройте свой архетип будущего' },
            ja: { name: '10年後のあなた', shortDesc: '未来の自分を発見する' },
            es: { name: '10 Años en el Futuro', shortDesc: 'Descubre tu yo futuro' },
            pt: { name: '10 Anos no Futuro', shortDesc: 'Descubra seu futuro pessoal' },
            id: { name: '10 Tahun Kemudian', shortDesc: 'Temukan diri masa depan Anda' },
            tr: { name: '10 Yıl Sonra', shortDesc: 'Gelecek öz-arketipi keşfedin' },
            de: { name: 'In 10 Jahren', shortDesc: 'Entdecke dein zukünftiges Selbst' },
            fr: { name: '10 Ans Plus Tard', shortDesc: 'Découvrez votre futur moi' }
        }
    }
];

const CATEGORIES = {
    all: { name: '전체', icon: '🏠', i18n: { en: 'All', zh: '全部', hi: 'सभी', ru: 'Все', ja: 'すべて', es: 'Todo', pt: 'Tudo', id: 'Semua', tr: 'Tümü', de: 'Alle', fr: 'Tout' } },
    game: { name: '게임', icon: '🎮', i18n: { en: 'Games', zh: '游戏', hi: 'गेम्स', ru: 'Игры', ja: 'ゲーム', es: 'Juegos', pt: 'Jogos', id: 'Game', tr: 'Oyunlar', de: 'Spiele', fr: 'Jeux' } },
    brain: { name: '두뇌훈련', icon: '🧠', i18n: { en: 'Brain Train', zh: '脑训练', hi: 'मस्तिष्क प्रशिक्षण', ru: 'Тренировка мозга', ja: '脳トレ', es: 'Entrena tu Cerebro', pt: 'Treino Cerebral', id: 'Latihan Otak', tr: 'Beyin Antrenmanı', de: 'Gehirntraining', fr: 'Entraînement Cérébral' } },
    test: { name: '심리테스트', icon: '🔮', i18n: { en: 'Tests', zh: '心理测试', hi: 'मनोविज्ञान परीक्षण', ru: 'Тесты', ja: '心理テスト', es: 'Tests de Psicología', pt: 'Testes Psicológicos', id: 'Tes Psikologi', tr: 'Psikoloji Testleri', de: 'Psychologische Tests', fr: 'Tests Psychologiques' } },
    fortune: { name: '운세점술', icon: '✨', i18n: { en: 'Fortune', zh: '运势占卜', hi: 'भाग्य', ru: 'Гадание', ja: '運勢', es: 'Fortuna', pt: 'Fortuna', id: 'Keberuntungan', tr: 'Fal', de: 'Wahrsagung', fr: 'Fortune' } },
    tool: { name: '계산기', icon: '🧮', i18n: { en: 'Calculators', zh: '计算器', hi: 'कैलकुलेटर', ru: 'Калькуляторы', ja: '計算機', es: 'Calculadoras', pt: 'Calculadoras', id: 'Kalkulator', tr: 'Hesap Makinesi', de: 'Taschenrechner', fr: 'Calculatrices' } },
    wellness: { name: '웰빙', icon: '🧘', i18n: { en: 'Wellness', zh: '健康', hi: 'कल्याण', ru: 'Благополучие', ja: 'ウェルネス', es: 'Bienestar', pt: 'Bem-estar', id: 'Kesejahteraan', tr: 'Sağlık', de: 'Wohlbefinden', fr: 'Bien-être' } },
    dev: { name: '개발자', icon: '💻', i18n: { en: 'Developer', zh: '开发者', hi: 'डेवलपर', ru: 'Разработчик', ja: '開発者', es: 'Desarrollador', pt: 'Desenvolvedor', id: 'Pengembang', tr: 'Geliştirici', de: 'Entwickler', fr: 'Développeur' } }
};

// Helper: get localized app name/desc
function getAppName(app, lang) {
    if (lang && lang !== 'ko' && app.i18n && app.i18n[lang]) return app.i18n[lang].name || app.name;
    return app.name;
}
function getAppDesc(app, lang) {
    if (lang && lang !== 'ko' && app.i18n && app.i18n[lang]) return app.i18n[lang].shortDesc || app.shortDesc;
    return app.shortDesc;
}
function getCategoryName(catKey, lang) {
    var cat = CATEGORIES[catKey];
    if (!cat) return catKey;
    if (lang && lang !== 'ko' && cat.i18n && cat.i18n[lang]) return cat.i18n[lang];
    return cat.name;
}
