// App data for the portal
// URLs can be updated to GitHub Pages URLs when deployed
const APP_DATA = [
    {
        id: 'quiz-app',
        name: '지식 퀴즈',
        shortDesc: '일반상식 테스트',
        description: '재미있는 지식 퀴즈로 상식을 쌓아보세요! 100개의 다양한 문제에 도전하세요.',
        icon: '🧠',
        color: '#667eea',
        category: 'quiz',
        tags: ['퀴즈', '상식', '교육', '게임'],
        url: 'https://swp1234.github.io/quiz-app/',
        isNew: false,
        isPopular: true
    },
    {
        id: 'shopping-calc',
        name: '글로벌 쇼핑 계산기',
        shortDesc: '환율/관세/팁 계산',
        description: '해외직구와 여행을 위한 환율, 관세, 팁 계산기. 실시간 환율 API 연동.',
        icon: '🛒',
        color: '#f39c12',
        category: 'tool',
        tags: ['환율', '계산기', '관세', '해외직구', '여행'],
        url: 'https://swp1234.github.io/shopping-calc/',
        isNew: false,
        isPopular: true
    },
    {
        id: 'detox-timer',
        name: '디지털 디톡스 타이머',
        shortDesc: '스마트폰 사용 관리',
        description: '스마트폰 사용 시간을 줄이고 집중력을 높이세요. 통계와 배지 시스템.',
        icon: '⏰',
        color: '#00b894',
        category: 'life',
        tags: ['타이머', '디톡스', '집중', '생산성'],
        url: 'https://swp1234.github.io/detox-timer/',
        isNew: false,
        isPopular: false
    },
    {
        id: 'dream-fortune',
        name: '꿈해몽 & 운세',
        shortDesc: 'AI 꿈 해석 & 오늘의 운세',
        description: 'AI 꿈해몽과 오늘의 운세를 확인하세요. 별자리, 타로, 꿈 해석까지!',
        icon: '🔮',
        color: '#9b59b6',
        category: 'fortune',
        tags: ['운세', '꿈해몽', '타로', '별자리'],
        url: 'https://swp1234.github.io/dream-fortune/',
        isNew: false,
        isPopular: true
    },
    {
        id: 'affirmation',
        name: '일일 긍정 확언 카드',
        shortDesc: '매일 새로운 긍정 메시지',
        description: '매일 새로운 긍정 확언으로 하루를 시작하세요. 자존감, 동기부여, 감사.',
        icon: '💖',
        color: '#e91e63',
        category: 'life',
        tags: ['긍정', '확언', '동기부여', '자존감', '명언'],
        url: 'https://swp1234.github.io/affirmation/',
        isNew: false,
        isPopular: false
    },
    {
        id: 'lottery',
        name: '행운의 번호 생성기',
        shortDesc: '로또/연금복권 번호',
        description: '로또 6/45, 연금복권 행운 번호 생성기. 번호 통계 분석, 반자동 모드.',
        icon: '🎰',
        color: '#e74c3c',
        category: 'fortune',
        tags: ['로또', '복권', '번호', '행운', '추첨'],
        url: 'https://swp1234.github.io/lottery/',
        isNew: false,
        isPopular: true
    },
    {
        id: 'dday-counter',
        name: 'D-Day 카운터',
        shortDesc: '중요한 날짜 카운트다운',
        description: '중요한 날짜를 D-Day로 관리하세요. 생일, 기념일, 시험일 카운트다운.',
        icon: '📅',
        color: '#3498db',
        category: 'tool',
        tags: ['D-Day', '카운트다운', '기념일', '일정'],
        url: 'https://swp1234.github.io/dday-counter/',
        isNew: false,
        isPopular: false
    },
    {
        id: 'mbti-tips',
        name: 'MBTI 궁합 & 팁',
        shortDesc: 'MBTI 유형별 분석',
        description: 'MBTI 유형별 궁합, 성격 분석, 연애/직장 팁을 확인하세요.',
        icon: '🧩',
        color: '#1abc9c',
        category: 'fortune',
        tags: ['MBTI', '성격', '궁합', '심리테스트'],
        url: 'https://swp1234.github.io/mbti-tips/',
        isNew: false,
        isPopular: true
    },
    {
        id: 'white-noise',
        name: '백색소음 플레이어',
        shortDesc: '집중/수면용 배경음',
        description: '집중, 수면, 명상을 위한 백색소음 & 자연소리 플레이어.',
        icon: '🎵',
        color: '#2c3e50',
        category: 'life',
        tags: ['백색소음', '수면', '집중', '명상', 'ASMR'],
        url: 'https://swp1234.github.io/white-noise/',
        isNew: false,
        isPopular: false
    },
    {
        id: 'dev-quiz',
        name: '개발자 퀴즈',
        shortDesc: '코딩/IT 전문 퀴즈',
        description: '개발자를 위한 코딩/IT 퀴즈. JavaScript, Python, 네트워크 등.',
        icon: '💻',
        color: '#27ae60',
        category: 'quiz',
        tags: ['개발자', '코딩', 'IT', '프로그래밍', '퀴즈'],
        url: 'https://swp1234.github.io/dev-quiz/',
        isNew: false,
        isPopular: false
    },
    {
        id: 'tax-refund-preview',
        name: '연말정산 미리보기',
        shortDesc: '환급액 시뮬레이션',
        description: '연말정산 예상 환급액을 미리 계산해보세요. 소득공제, 세액공제 반영.',
        icon: '💰',
        color: '#3742fa',
        category: 'tool',
        tags: ['연말정산', '환급', '세금', '계산기'],
        url: 'https://swp1234.github.io/tax-refund-preview/',
        isNew: true,
        isPopular: false
    },
    {
        id: 'unit-converter',
        name: '단위 변환기 Pro',
        shortDesc: '평수, 무게, 온도 변환',
        description: '평수, 무게, 온도, 부피 등 다양한 단위를 실시간으로 변환합니다.',
        icon: '📐',
        color: '#2ed573',
        category: 'tool',
        tags: ['단위', '변환', '평수', '온도', '무게'],
        url: 'https://swp1234.github.io/unit-converter/',
        isNew: true,
        isPopular: false
    },
    {
        id: 'sky-runner',
        name: 'Sky Runner',
        shortDesc: '우주 비행 아케이드 게임',
        description: '우주선을 조종해 장애물을 피하세요! 원탭 조작의 중독성 캐주얼 아케이드 게임.',
        icon: '🚀',
        color: '#5f27cd',
        category: 'quiz',
        tags: ['게임', '아케이드', '우주', '캐주얼', 'Flappy'],
        url: 'https://swp1234.github.io/sky-runner/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'emotion-temp',
        name: '감정 온도계 테스트',
        shortDesc: '나의 감정 온도는 몇 도?',
        description: '10가지 질문으로 알아보는 나의 감정 온도! 16가지 유형 중 당신은? 결과 이미지 저장 & 공유.',
        icon: '🌡️',
        color: '#e07a5f',
        category: 'fortune',
        tags: ['심리테스트', '감정', '성격', '바이럴', 'HSP', '감정온도'],
        url: 'https://swp1234.github.io/emotion-temp/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'mbti-love',
        name: 'MBTI 연애 궁합 테스트',
        shortDesc: '나의 연애 스타일은? 💕',
        description: '12가지 질문으로 알아보는 나의 MBTI 연애 스타일! 16가지 유형과 256가지 궁합표. 나와 찰떡궁합인 유형은?',
        icon: '💕',
        color: '#e74c3c',
        category: 'fortune',
        tags: ['MBTI', '연애', '궁합', '심리테스트', '연애스타일'],
        url: 'https://swp1234.github.io/mbti-love/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'hsp-test',
        name: 'HSP 민감성 테스트',
        shortDesc: '나는 고감수성자일까?',
        description: '20가지 질문으로 알아보는 HSP 민감도! 5가지 유형과 감각별 분석. 2026 메타센싱 트렌드.',
        icon: '🧠',
        color: '#7c3aed',
        category: 'fortune',
        tags: ['HSP', '민감성', '심리테스트', '메타센싱', '고감수성자', '감정'],
        url: 'https://swp1234.github.io/hsp-test/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'love-frequency',
        name: '사랑 주파수 테스트',
        shortDesc: '나의 사랑은 몇 Hz?',
        description: '솔페지오 주파수 기반 사랑 유형 테스트! 10문항으로 나의 사랑 주파수를 찾고 실제 주파수 음악도 들어보세요.',
        icon: '💕',
        color: '#e91e63',
        category: 'fortune',
        tags: ['사랑', '주파수', '연애', '심리테스트', '솔페지오', '528Hz', '궁합'],
        url: 'https://swp1234.github.io/love-frequency/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'stack-tower',
        name: 'Stack Tower',
        shortDesc: '타이밍 블록 쌓기 게임',
        description: '완벽한 타이밍으로 블록을 쌓아 하늘 끝까지! 5가지 테마와 20개 칭호에 도전하세요.',
        icon: '🏗️',
        color: '#3498db',
        category: 'quiz',
        tags: ['게임', '아케이드', '타이밍', '블록', '캐주얼', '타워'],
        url: 'https://swp1234.github.io/stack-tower/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'kpop-position',
        name: 'K-POP 포지션 테스트',
        shortDesc: '나의 아이돌 포지션은?',
        description: '12가지 질문으로 알아보는 나의 K-POP 포지션! 메인보컬, 리더, 래퍼, 댄서, 비주얼, 막내, 올라운더 중 당신은?',
        icon: '🎤',
        color: '#ff2d78',
        category: 'fortune',
        tags: ['KPOP', '포지션', '아이돌', '심리테스트', 'BTS', 'BLACKPINK'],
        url: 'https://swp1234.github.io/kpop-position/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'emoji-merge',
        name: '이모지 머지',
        shortDesc: '이모지 진화 퍼즐 게임',
        description: '같은 이모지를 합쳐 진화시키세요! 🥚→🐣→🐥→🦅→🐉→👑 알에서 용까지! 씨앗→세계수, 물방울→은하 4가지 진화 체인.',
        icon: '🧬',
        color: '#f4a261',
        category: 'quiz',
        tags: ['이모지', '머지', '진화', '퍼즐', '게임', '2048', '캐주얼'],
        url: 'https://swp1234.github.io/emoji-merge/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'zigzag-runner',
        name: 'Zigzag Runner',
        shortDesc: '방향 전환 아케이드 게임',
        description: '탭 한 번으로 방향 전환! 끝없는 지그재그 길 위에서 코인을 모으며 달리세요. 5가지 테마와 20개 칭호.',
        icon: '🏃',
        color: '#ff6348',
        category: 'quiz',
        tags: ['게임', '아케이드', '지그재그', '러너', '캐주얼', '원탭'],
        url: 'https://swp1234.github.io/zigzag-runner/',
        isNew: true,
        isPopular: true
    },
    {
        id: 'past-life',
        name: '전생 직업 테스트',
        shortDesc: '나의 전생은 무엇이었을까?',
        description: '10문항으로 알아보는 나의 전생 직업! 기사단장, 해적 선장, 르네상스 화가... 8가지 전생 유형과 궁합까지.',
        icon: '🗡️',
        color: '#C9A96E',
        category: 'fortune',
        tags: ['전생', '심리테스트', '바이럴', '궁합', '전생직업'],
        url: 'https://swp1234.github.io/past-life/',
        isNew: true,
        isPopular: true
    }
];

const CATEGORIES = {
    all: { name: '전체', icon: '🏠' },
    quiz: { name: '퀴즈/게임', icon: '🎮' },
    fortune: { name: '운세/테스트', icon: '🔮' },
    tool: { name: '계산기/도구', icon: '🧮' },
    life: { name: '라이프', icon: '🧘' }
};
